m = read.table('test_data/fig1_mean.dat', head=F)
r = read.table('test_data/fig1_rms.dat', head=F)

con = pipe('./testexe', 'r')
f = read.table(con, head=F)
close(con)

png('test.png')
plot(f[,1], sqrt(f[,3]), type='l', col=4, lty=2, log='x', xlab=expression(mu), ylab='Contribution per bin to Cstat', main='cash_mod_expectations')
points(r, col=4)
points(f[,1], f[,2], type='l', col=2)
points(m, col=2)
legend('topleft', c('Kaastra 2017 fig 1', 'cstat lib'), pch=c(1,NA), lty=c(NA,1))
legend('bottomright', c('mean','RMS'), lty=c(1,2), col=c(2,4))
dev.off()
